In [1]:
import numpy as np

In [4]:
K = np.array([[1,2,3],[4,5,6],[11,9,8]])
letters = [ch for ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
plain_text = input("Enter plain_text: ").upper()
plain_text = "".join(plain_text.split(" "))

Enter plain_text: block cipher


In [5]:
while(True):
    if(len(plain_text)%3==0):
       break
    plain_text+="X"

In [6]:
PT = [letters.index(ch) for ch in plain_text]
PT = np.array(PT)
PT.shape = (-1,3)
print(PT)

[[ 1 11 14]
 [ 2 10  2]
 [ 8 15  7]
 [ 4 17 23]]


In [7]:
result_mat = K.dot(PT.T)
result_mat = result_mat%26
print(result_mat)

[[13  2  7  3]
 [13 18 19  5]
 [14 24 19 17]]


In [8]:
result = result_mat.ravel()
cipher = "".join([letters[n] for n in result])
print(cipher)

NCHDNSTFOYTR
